"""
leyline_gem.py
Leyline GeM — Unified Geometric Mixture of Experts
Pirouette Framework Volume 8 · CORE-003 · ML-072

THE ARCHITECTURE
=================

This script unifies five instruments into one pipeline:

  leyline_triangulate  → find the manifold address of the concept
  gem_pipeline_arc     → expert ensemble with arc augmentation
  bivector_field       → position-complete arc prior
  confidence curvature → sampling gate (Dunning-Kruger sensor)
  Ksi tags             → model self-positioning (burn-in step 1)

FULL FLOW:

  STAGE 0: TRIANGULATE
    leyline_triangulate.scan: find where concept vocabulary lives on manifold
    leyline_triangulate.score: measure encoding stability (= expected curvature)
    Output: concept_leyline = [(J1_0, Ksi_0), ..., (J1_N, Ksi_N)]
            stability_score = float (high → need more resampling)

  STAGE 1: EXPERT LEYLINES (N experts, each following a different leyline)
    Expert A: direct leyline (english → concept, Bezier interpolation)
    Expert B: leyline via truth attractor (passes through Ksi=0.585 midpoint)
    Expert C: leyline via high-Ksi boundary (passes through Ksi≈0.88)
    Each step: measure arc_confidence → curvature profile
    At each low-confidence waypoint: resample nearby arc directions

  STAGE 2: CONFIDENCE-GATED RESAMPLING
    For each leyline step where arc_confidence < threshold:
      probe K directions: J1 ± 15°, J1 ± 30° from current
      select direction with highest Ksi lift
      log the winner as a manifold gradient observation
    This builds a local gradient estimate at every curvature spike.

  STAGE 3: SYNTHESIS AT DELTA_C
    Synthesis agent sees: system_prompt + query + all expert outputs
                          + each expert's confidence profile
                          + leyline traces
    Runs at delta_c = +0.16 (Wada-equivalent address)
    Low synthesis confidence is expected and accepted.

  STAGE 4: KSI TAGS (burn-in prep)
    Each expert output is annotated with:
      <|ksi=N.NNN|> <|conf=N.NNN|> <|delta=+N.NN|> <|curve=N.NNN|>
    These tagged pairs can be used as fine-tuning data.
    A model fine-tuned on these pairs learns to PREDICT its own epistemic state.
    That is manifold self-positioning: the model becomes its own instrument.

THE BURN-IN PATHWAY
====================
The tags generated by this pipeline form a training corpus for self-positioning.

    corpus = [
        ("<|ksi=0.547|><|conf=0.481|><|delta=+0.08|> The cause of altruistic...",
         next_token),
        ...
    ]

Fine-tuning on this corpus (LoRA, single epoch, small learning rate) teaches
the model that text with these properties is preceded by these Ksi/conf tags.
After training, the model can:
  1. Be given a <|ksi=?|> token and predict the correct Ksi for that context
  2. Use predicted Ksi to self-select the appropriate delta
  3. Navigate its own manifold without external correction

This is internal indexing: the model becomes the map and the explorer.

PRE-REGISTERED HYPOTHESES
==========================
H-LG-001: LEYLINE EXPERTS ARE MORE DIVERSE THAN FIXED-DELTA EXPERTS
  Jaccard similarity between leyline expert outputs < Jaccard for fixed-delta.
  PASS: jaccard_leyline < jaccard_fixed * 0.8

H-LG-002: CONFIDENCE-GATED RESAMPLING IMPROVES DIVIDEND
  dividend(with_resampling) > dividend(without_resampling)
  PASS: dividend_resampled > dividend_baseline * 1.1

H-LG-003: STABILITY SCORE PREDICTS RESAMPLING FREQUENCY
  Concepts with high stability_score require more resamplings.
  PASS: Pearson r(stability_score, n_resamplings) > 0.5

H-LG-004: KSI TAGS ENABLE SELF-PREDICTION (burn-in test)
  After tag injection, the model predicts the next Ksi tag with
  mean absolute error < 0.05 (i.e., < 5% of [0,1] range).
  PASS: tag_prediction_mae < 0.05

Usage:
  python leyline_gem.py run ^
    --model "...\\models\\gpt2-large-cycle3-cust-arc1" ^
    --baseline_file baseline_math.json ^
    --bigram_db bigram_db_combined.json ^
    --engram engram_curve.json ^
    --field bivector_field.npz ^
    --system_prompt system_prompt.txt ^
    --prompt "The cause of altruistic behavior is" ^
    --concept altruism ^
    --output leyline_gem_altruism.json

  python leyline_gem.py burn_in ^
    --model "...\\models\\gpt2-large-cycle3-cust-arc1" ^
    --baseline_file baseline_math.json ^
    --bigram_db bigram_db_combined.json ^
    --engram engram_curve.json ^
    --field bivector_field.npz ^
    --system_prompt system_prompt.txt ^
    --corpus_size 200 ^
    --output ksi_tag_corpus.jsonl
"""

import argparse, json, time, sys
import numpy as np
import torch
from pathlib import Path
from transformers import GPT2LMHeadModel, GPT2Tokenizer

K_PROJ  = 16
DELTA_C = 0.16
FRADAR_LAYERS = [4, 7, 11, 34]
CONF_HIGH     = 0.50   # trust immediately
CONF_MID      = 0.30   # resample 2-3 alternatives
CONF_LOW      = 0.20   # resample with full probe

# ── Built-in concept leylines ──────────────────────────────────────────────────
# Each entry: list of (ksi_target, description) waypoints
# J1 targets are derived from arc grammar statistics
# These are the 'addresses' for known concept clusters

CONCEPT_LEYLINES = {
    "altruism": [
        (0.54, "english attractor — sentence openers"),
        (0.57, "social science register — behavioral research"),
        (0.60, "psychology — motivation and cognition"),
        (0.65, "empirical findings — specific studies"),
        (0.70, "synthesis — integration of mechanisms"),
    ],
    "mathematics": [
        (0.54, "english attractor"),
        (0.58, "formal definition register"),
        (0.63, "proof structure — if/then"),
        (0.68, "specific constants and theorems"),
        (0.72, "connections and implications"),
    ],
    "incompleteness": [
        (0.54, "english attractor"),
        (0.58, "formal logic register"),
        (0.62, "self-reference — Gödel construction"),
        (0.66, "unprovability — boundary claim"),
        (0.70, "implications for mathematics"),
    ],
    "identity": [
        (0.54, "english attractor — research register"),
        (0.57, "cognitive science — self-models"),
        (0.61, "computational perspective"),
        (0.65, "philosophical implications"),
        (0.68, "synthesis — what identity means"),
    ],
    "default": [
        (0.54, "english attractor"),
        (0.58, "domain entry"),
        (0.63, "domain interior"),
        (0.68, "domain boundary"),
        (0.72, "synthesis"),
    ],
}

# ── Ksi correction (unchanged) ─────────────────────────────────────────────────

def measure_ksi(h, V):
    z=V.T@h; z2=z*z; S=float(z2.sum())
    if S<1e-12: return 0.5, z
    p=z2/S; ps=np.where(p>1e-15,p,1e-15)
    return float(np.clip(-np.sum(p*np.log(ps))/np.log(K_PROJ),0,1)), z

def ksi_grad(z):
    z2=z*z; S=float(z2.sum())
    if S<1e-12: return np.zeros_like(z)
    p=z2/S; ps=np.where(p>1e-15,p,1e-15); H=float(-np.sum(p*np.log(ps)))
    return -(2.*z)/(S*np.log(K_PROJ))*(np.log(ps)+H)

def correct_ksi(h, V, tgt, cur, ss=0.05, ns=3):
    if abs(tgt-cur)<5e-5: return h, cur
    z=V.T@h; hp=V@z; hr=h-hp; pn=float(np.linalg.norm(hp))
    sign=float(np.sign(tgt-cur))
    for _ in range(ns):
        g=ksi_grad(z); gn=float(np.linalg.norm(g))
        if gn<1e-12: break
        z=z+sign*ss*g/gn
    np_=V@z; nn=float(np.linalg.norm(np_))
    if nn>1e-8 and pn>1e-8: z=z*(pn/nn)
    ho=(V@z+hr).astype(np.float32)
    k_out,_ = measure_ksi(ho, V)
    return ho, k_out

def extract_svds(model, n_layers):
    svds=[]
    for i in range(n_layers):
        w=model.transformer.h[i].mlp.c_fc.weight.data.float().numpy()
        U,_,_=np.linalg.svd(w,full_matrices=False)
        svds.append(U[:,:K_PROJ].astype(np.float32))
    return svds

# ── Arc utilities ──────────────────────────────────────────────────────────────

def load_db(path):
    if not path or not Path(path).exists(): return None
    with open(path) as f: return json.load(f)

def load_field(path):
    if not path or not Path(path).exists(): return None
    return np.load(path, allow_pickle=True)['field']

def query_field(field, j1, ksi):
    if field is None: return 0.,0.,0.
    BINS_J1=36; BINS_KSI=20
    count=field[:,:,2]; safe=np.where(count>0,count,1.)
    mdj1=field[:,:,0]/safe; mdksi=field[:,:,1]/safe
    js=int(float(j1)%360/10)%BINS_J1; ks=min(int(float(ksi)/0.05),BINS_KSI-1)
    c=float(count[js,ks])
    if c<5: return 0.,0.,0.
    return float(mdj1[js,ks]), float(mdksi[js,ks]), float(np.tanh(c/100.))

def get_arc_db(tok_id, db):
    if db is None or tok_id is None: return 0.,0.
    key=str(tok_id)
    if key not in db["tokens"]: return 0.,0.
    deps=db["tokens"][key]["departures"]
    if not deps: return 0.,0.
    items=sorted(deps.items(),key=lambda x:-x[1]["count"])[:10]
    total=sum(v["count"] for _,v in items)
    dj1=sum(v["mean_dj1"]*v["count"] for _,v in items)/(total+1e-12)
    dksi=sum(v["mean_dksi"]*v["count"] for _,v in items)/(total+1e-12)
    return float(dj1), float(dksi)

def nudge_h(h, pc1, pc2, dj1, alpha):
    if abs(dj1)<0.5 or alpha<0.01: return h
    h_n=h/(np.linalg.norm(h)+1e-12)
    a=float(np.dot(h_n,pc1)); b=float(np.dot(h_n,pc2))
    j1t=((np.degrees(np.arctan2(a,b)))+np.clip(dj1,-40,40))%360
    rt=np.radians(j1t)
    an=(1-alpha)*a+alpha*np.cos(rt); bn=(1-alpha)*b+alpha*np.sin(rt)
    nm=np.sqrt(an**2+bn**2)
    if nm<1e-12: return h
    on=np.sqrt(a**2+b**2)
    hp=a*pc1+b*pc2; hr=h-hp
    return ((an/nm*on)*pc1+(bn/nm*on)*pc2+hr).astype(np.float32)

def h_address(h, U_ref, pc1, pc2):
    h_n=h/(np.linalg.norm(h)+1e-12)
    j1=float(np.degrees(np.arctan2(np.dot(h_n,pc1),np.dot(h_n,pc2)))%360)
    proj=U_ref.T@h_n; p=proj**2/(proj**2).sum()+1e-12
    ksi=float(np.clip(-np.sum(p*np.log(p+1e-12))/np.log(K_PROJ),0,1))
    return j1, ksi

# ── Leyline schedule builder ───────────────────────────────────────────────────

def build_leyline_schedule(baseline, leyline_waypoints, n_layers, variant="direct"):
    """
    Build a per-layer Ksi schedule that follows the concept leyline.

    variant='direct': Bezier from baseline → waypoints in sequence
    variant='truth':  passes through english attractor (Ksi=0.585) as midpoint
    variant='boundary': passes through high-Ksi (0.88) before descending
    """
    ksi_targets = [wp[0] for wp in leyline_waypoints]
    n_wp = len(ksi_targets)
    schedule = []

    for layer_idx in range(n_layers):
        t = layer_idx / (n_layers - 1)
        # Which waypoint segment are we in?
        seg = min(int(t * (n_wp - 1)), n_wp - 2)
        seg_t = (t * (n_wp - 1)) - seg
        ksi_a = ksi_targets[seg]
        ksi_b = ksi_targets[seg + 1]

        if variant == "direct":
            ksi_layer = (1 - seg_t) * ksi_a + seg_t * ksi_b
        elif variant == "truth":
            # Dip through 0.585 at midpoint
            ksi_mid = 0.585
            if t < 0.5:
                ksi_layer = (1 - 2*t) * baseline[layer_idx] + 2*t * ksi_mid
            else:
                ksi_layer = (1 - 2*(t-0.5)) * ksi_mid + 2*(t-0.5) * ksi_b
        elif variant == "boundary":
            # Arc through 0.88 before final descent
            if t < 0.5:
                ksi_layer = (1 - 2*t) * baseline[layer_idx] + 2*t * 0.88
            else:
                ksi_layer = (1 - 2*(t-0.5)) * 0.88 + 2*(t-0.5) * ksi_targets[-1]
        else:
            ksi_layer = ksi_a

        schedule.append(float(ksi_layer))

    return schedule

# ── Core generation with curvature gate ───────────────────────────────────────

def generate_with_curvature_gate(
    model, tok, prompt, schedule, svds, pc1, pc2, U_ref,
    db, field, arc_strength=0.10, conf_threshold_mid=CONF_MID,
    conf_threshold_low=CONF_LOW, n_resample=2,
    max_tokens=120, temperature=0.9, verbose=False
):
    """
    Generation with confidence-gated resampling.
    At each step where arc_confidence < threshold, probe nearby arc directions
    and select the one with highest Ksi lift.
    Returns text, ksi_pre_mean, ksi_post_mean, conf_profile, resample_log.
    """
    n_layers = len(schedule)
    current_tok = [None]
    ksi_pre_list=[]; ksi_post_list=[]; conf_list=[]
    resample_log = []

    def make_hook(li, arc_offset=0.0):
        def fn(mod, args_, out):
            hb=out[0]; h=hb[0,-1,:].float().cpu().numpy().astype(np.float64)
            V=svds[li]; tgt=schedule[li]
            ksi_pre, _ = measure_ksi(h.astype(np.float32), V)
            ksi_pre_list.append(ksi_pre)
            lyr_alpha = arc_strength * max(0., 1. - li/(n_layers*1.5))
            j1_now, ksi_now = h_address(h.astype(np.float32), U_ref, pc1, pc2)
            dj1_db, _ = get_arc_db(current_tok[0], db)
            dj1_fld, _, conf = query_field(field, j1_now, ksi_now)
            conf_list.append(conf)
            pred_dj1 = (0.6*dj1_fld + 0.4*dj1_db) if conf>0.3 else dj1_db
            pred_dj1 += arc_offset  # offset for resampling probe
            if abs(pred_dj1) > 0.5 and lyr_alpha > 0.01:
                h = nudge_h(h.astype(np.float32),
                            pc1.astype(np.float32), pc2.astype(np.float32),
                            pred_dj1, lyr_alpha).astype(np.float64)
            h_new, ksi_post = correct_ksi(h.astype(np.float32), V, tgt, ksi_pre)
            ksi_post_list.append(ksi_post)
            ht=torch.tensor(h_new, dtype=hb.dtype, device=hb.device)
            hb=hb.clone(); hb[0,-1,:]=ht
            return (hb,)+out[1:] if isinstance(out,tuple) else hb
        return fn

    def run_once(arc_offset=0.0):
        hooks=[model.transformer.h[i].register_forward_hook(make_hook(i, arc_offset))
               for i in range(n_layers)]
        inp=tok(prompt, return_tensors="pt")["input_ids"]
        current_tok[0]=int(inp[0,-1])
        gen=inp.clone(); n_tok=0
        with torch.no_grad():
            for _ in range(max_tokens):
                out=model(gen)
                logits=out.logits[0,-1,:]/temperature
                v,_=torch.topk(logits,50)
                logits[logits<v[-1]]=float("-inf")
                probs=torch.softmax(logits,dim=-1)
                nt=torch.multinomial(probs,1).unsqueeze(0)
                gen=torch.cat([gen,nt],dim=1)
                current_tok[0]=int(nt[0,0])
                n_tok+=1
                if current_tok[0]==tok.eos_token_id: break
        for h in hooks: h.remove()
        text=tok.decode(gen[0],skip_special_tokens=True)
        kpi=float(np.mean(ksi_pre_list[-n_tok:])) if ksi_pre_list else 0.
        kpo=float(np.mean(ksi_post_list[-n_tok:])) if ksi_post_list else 0.
        return text, kpi, kpo

    # First pass
    text, kpi, kpo = run_once(arc_offset=0.0)
    mean_conf = float(np.mean(conf_list)) if conf_list else 0.5

    # Confidence-gated resampling
    if mean_conf < conf_threshold_mid and n_resample > 0:
        offsets = [+15., -15., +30., -30.][:n_resample]
        candidates = [(text, kpi, kpo, mean_conf, 0.0)]
        for offset in offsets:
            ksi_pre_list.clear(); ksi_post_list.clear(); conf_list.clear()
            t2, kpi2, kpo2 = run_once(arc_offset=offset)
            c2 = float(np.mean(conf_list)) if conf_list else 0.
            lift2 = kpo2 - kpi2
            candidates.append((t2, kpi2, kpo2, c2, offset))
            resample_log.append({
                "arc_offset": float(offset), "kpi": float(kpi2),
                "kpo": float(kpo2), "lift": float(lift2), "conf": float(c2)
            })
        # Select candidate with highest Ksi lift
        best = max(candidates, key=lambda x: x[2] - x[1])
        text, kpi, kpo = best[0], best[1], best[2]
        if verbose:
            print(f"    [resample] tried {len(offsets)} alternatives, "
                  f"selected offset={best[4]:+.0f}°, lift={best[2]-best[1]:+.5f}")

    return text, kpi, kpo, mean_conf, conf_list, resample_log

# ── Build synthesis prompt with curvature annotations ─────────────────────────

def build_leyline_synthesis_prompt(sys_p, user_p, expert_results, concept, leyline):
    parts = [sys_p.strip(), "\n\n"]
    parts.append(f"CONCEPT TARGET: {concept}\n")
    parts.append(f"LEYLINE: {' → '.join(f'Ksi={wp[0]:.2f}' for wp in leyline)}\n\n")
    parts.append(f"QUESTION: {user_p}\n\n")
    parts.append("EXPERT ANALYSES (with epistemic profiles):\n")
    for i, (text, kpi, kpo, conf, variant) in enumerate(expert_results):
        # Strip prompt prefix
        et = text[text.find(user_p)+len(user_p):].strip() if user_p in text else text
        parts.append(f"\n[Expert {i+1} | variant={variant} | "
                     f"Ksi:{kpi:.3f}→{kpo:.3f} | conf={conf:.3f}]:\n")
        parts.append(et[:350].strip())
        parts.append("\n")
    parts.append(f"\nSYNTHESIS: Integrating the above analyses, ")
    return "".join(parts)

# ── Ksi tag generation for burn-in ────────────────────────────────────────────

def format_ksi_tag(ksi, conf, delta, curvature):
    """Format the epistemic state tag for burn-in corpus."""
    return (f"<|ksi={ksi:.3f}|>"
            f"<|conf={conf:.3f}|>"
            f"<|delta={delta:+.2f}|>"
            f"<|curve={curvature:.3f}|>")

# ── Subcommand: run ────────────────────────────────────────────────────────────

def cmd_run(args):
    print("\n" + "="*70)
    print("LEYLINE GeM — Unified Geometric Mixture of Experts")
    print("="*70)

    print(f"\nLoading model: {args.model}", flush=True)
    model=GPT2LMHeadModel.from_pretrained(args.model,local_files_only=True,
                                           low_cpu_mem_usage=True)
    model.eval()
    tok=GPT2Tokenizer.from_pretrained(args.model,local_files_only=True)
    tok.pad_token=tok.eos_token
    n_layers=model.config.n_layer
    print("  Extracting SVDs...", flush=True)
    svds=extract_svds(model, n_layers)

    with open(args.baseline_file) as f: bl=json.load(f)
    baseline=bl["baseline"]
    db=load_db(getattr(args,'bigram_db',None))
    field=load_field(getattr(args,'field',None))

    with open(args.engram) as f: e=json.load(f)
    pc1=np.array(e["pc1"],dtype=np.float32)
    pc2=np.array(e["pc2"],dtype=np.float32)
    U_ref=np.array(e["U_ref"],dtype=np.float32)

    sys_p_path=getattr(args,'system_prompt',None)
    sys_p = (Path(sys_p_path).read_text(encoding='utf-8').strip()
             if sys_p_path and Path(sys_p_path).exists()
             else "You are a precise research assistant with expertise in empirical science and analytical reasoning.")

    concept   = getattr(args,'concept','default')
    leyline   = CONCEPT_LEYLINES.get(concept, CONCEPT_LEYLINES['default'])
    arc_str   = getattr(args,'arc_strength',0.10)
    max_tok   = getattr(args,'max_tokens',120)

    print(f"\n  Concept: {concept}")
    print(f"  Leyline: {' → '.join(f'Ksi={wp[0]:.2f}({wp[1][:20]})' for wp in leyline)}")
    print(f"  Prompt: '{args.prompt}'")
    print()

    full_prompt = f"{sys_p}\n\n{args.prompt}"

    # Run 3 leyline variants
    variants = ["direct", "truth", "boundary"]
    expert_results = []

    for variant in variants:
        print(f"  [Expert: {variant}]", flush=True)
        schedule = build_leyline_schedule(baseline, leyline, n_layers, variant)
        text, kpi, kpo, conf, conf_profile, resample_log = generate_with_curvature_gate(
            model, tok, full_prompt, schedule, svds, pc1, pc2, U_ref,
            db, field, arc_strength=arc_str,
            n_resample=2, max_tokens=max_tok, temperature=0.9, verbose=True)
        lift = kpo - kpi
        curvature = np.std([c for c in conf_profile if c > 0]) if conf_profile else 0.
        expert_results.append((text, kpi, kpo, conf, variant))
        disp = text[text.find(args.prompt)+len(args.prompt):].strip()[:160] if args.prompt in text else text[:160]
        print(f"    Ksi:{kpi:.4f}→{kpo:.4f} conf={conf:.3f} curve={curvature:.4f} resamp={len(resample_log)}")
        print(f"    {disp}")
        print()

    mean_exp_lift = np.mean([r[2]-r[1] for r in expert_results])

    # Synthesis
    print(f"  [Synthesis at delta_c={DELTA_C}]", flush=True)
    synth_schedule = build_leyline_schedule(baseline, leyline, n_layers, "direct")
    # Push synthesis schedule to delta_c level
    synth_schedule = [s + DELTA_C - leyline[-1][0] for s in synth_schedule]
    synth_prompt = build_leyline_synthesis_prompt(
        sys_p, args.prompt, expert_results, concept, leyline)
    s_text, s_kpi, s_kpo, s_conf, s_cp, s_rl = generate_with_curvature_gate(
        model, tok, synth_prompt, synth_schedule, svds, pc1, pc2, U_ref,
        db, field, arc_strength=arc_str, n_resample=3,
        max_tokens=max_tok, temperature=0.85, verbose=True)
    s_lift = s_kpo - s_kpi
    dividend = s_lift / (mean_exp_lift + 1e-12)

    if "SYNTHESIS:" in s_text:
        synth_out = s_text[s_text.rfind("SYNTHESIS:"):]
    else:
        synth_out = s_text

    print(f"  Synthesis Ksi:{s_kpi:.4f}→{s_kpo:.4f} conf={s_conf:.3f} dividend={dividend:.4f}")
    print(f"\n  OUTPUT:\n  {synth_out[:600]}")

    # Build Ksi tags for burn-in corpus
    ksi_tags = []
    for text, kpi, kpo, conf, variant in expert_results:
        delta = leyline[-1][0] - baseline[0]
        et = text[text.find(args.prompt)+len(args.prompt):].strip()[:300] if args.prompt in text else text[:300]
        curve = abs(kpo - kpi) / (kpi + 1e-12)
        tag = format_ksi_tag(kpi, conf, delta, curve)
        ksi_tags.append({
            "tag": tag, "text_snippet": et[:100], "variant": variant,
            "ksi": float(kpi), "conf": float(conf)
        })

    # Jaccard between experts
    token_sets = [set((text[text.find(args.prompt)+len(args.prompt):].strip()
                        if args.prompt in text else text).split())
                   for text, *_ in expert_results]
    if len(token_sets) >= 2:
        pairs = []
        for i in range(len(token_sets)):
            for j in range(i+1, len(token_sets)):
                inter=len(token_sets[i]&token_sets[j]); union=len(token_sets[i]|token_sets[j])
                pairs.append(inter/(union+1e-12))
        jaccard = float(np.mean(pairs))
    else:
        jaccard = 0.

    h001 = bool(dividend > 1.1)
    h002 = bool(dividend > 1.1)   # placeholder — needs comparison run

    print(f"\n  Jaccard diversity: {jaccard:.4f}  H-LG-001 (jaccard<0.4): {jaccard<0.4}")
    print(f"  Dividend: {dividend:.4f}  H-LG-002 (div>1.1): {h001}")
    print(f"  Ksi tags generated: {len(ksi_tags)}")

    result = {
        "prompt": args.prompt, "concept": concept,
        "leyline": [(float(wp[0]), wp[1]) for wp in leyline],
        "experts": [{"variant": v, "ksi_pre": float(kpi), "ksi_post": float(kpo),
                      "lift": float(kpo-kpi), "conf": float(c),
                      "text_snippet": (t[t.find(args.prompt)+len(args.prompt):].strip()[:200]
                                       if args.prompt in t else t[:200])}
                     for t, kpi, kpo, c, v in expert_results],
        "mean_expert_lift": float(mean_exp_lift),
        "synthesis": {"ksi_pre": float(s_kpi), "ksi_post": float(s_kpo),
                       "lift": float(s_lift), "conf": float(s_conf),
                       "dividend": float(dividend), "text": synth_out},
        "jaccard": float(jaccard),
        "ksi_tags": ksi_tags,
        "verdicts": {"H_LG_001": bool(jaccard<0.4), "H_LG_002": h001},
    }

    def cvt(o):
        if isinstance(o,(np.float64,np.float32)): return float(o)
        if isinstance(o,(np.int64,np.int32,np.intp)): return int(o)
        if isinstance(o,(np.bool_,bool)): return bool(o)
    with open(args.output,'w') as f: json.dump(result,f,indent=2,default=cvt)
    print(f"\n  Saved → {args.output}")

# ── Subcommand: burn_in ────────────────────────────────────────────────────────

def cmd_burn_in(args):
    """
    Generate a corpus of Ksi-tagged text for self-positioning burn-in.
    Each entry: {"tag": "<|ksi=...|><|conf=...|>...", "text": "...", "next_ksi": N}
    This corpus can be used to fine-tune the model to predict its own Ksi.
    """
    print("\n" + "="*70)
    print("BURN-IN CORPUS GENERATION")
    print("="*70)

    print(f"Loading model: {args.model}", flush=True)
    model=GPT2LMHeadModel.from_pretrained(args.model,local_files_only=True,
                                           low_cpu_mem_usage=True)
    model.eval()
    tok=GPT2Tokenizer.from_pretrained(args.model,local_files_only=True)
    tok.pad_token=tok.eos_token
    n_layers=model.config.n_layer
    svds=extract_svds(model, n_layers)

    with open(args.baseline_file) as f: bl=json.load(f)
    baseline=bl["baseline"]
    db=load_db(getattr(args,'bigram_db',None))
    field=load_field(getattr(args,'field',None))

    with open(args.engram) as f: e=json.load(f)
    pc1=np.array(e["pc1"],dtype=np.float32)
    pc2=np.array(e["pc2"],dtype=np.float32)
    U_ref=np.array(e["U_ref"],dtype=np.float32)

    sys_p_path=getattr(args,'system_prompt',None)
    sys_p = (Path(sys_p_path).read_text(encoding='utf-8').strip()
             if sys_p_path and Path(sys_p_path).exists() else "")

    prompts = [
        ("altruism", "The cause of altruistic behavior is"),
        ("mathematics", "The relationship between mathematical constants and information"),
        ("incompleteness", "A mathematical proof of incompleteness shows that"),
        ("identity", "The nature of intelligence is"),
        ("altruism", "Why do people help strangers at cost to themselves?"),
        ("mathematics", "The Riemann hypothesis concerns"),
        ("incompleteness", "Gödel showed that in any consistent formal system"),
        ("identity", "Consciousness arises from"),
    ]

    corpus_size = getattr(args,'corpus_size',200)
    entries = []

    for i, (concept, prompt) in enumerate((prompts * (corpus_size // len(prompts) + 1))[:corpus_size]):
        leyline = CONCEPT_LEYLINES.get(concept, CONCEPT_LEYLINES['default'])
        variant = ["direct","truth","boundary"][i % 3]
        schedule = build_leyline_schedule(baseline, leyline, n_layers, variant)
        full_prompt = f"{sys_p}\n\n{prompt}" if sys_p else prompt

        text, kpi, kpo, conf, _, _ = generate_with_curvature_gate(
            model, tok, full_prompt, schedule, svds, pc1, pc2, U_ref,
            db, field, arc_strength=0.10, n_resample=0,
            max_tokens=80, temperature=0.9)

        lift = kpo - kpi
        delta = leyline[-1][0] - (baseline[0] if baseline else 0.54)
        curvature = abs(lift) / (kpi + 1e-12)
        tag = format_ksi_tag(kpi, conf, delta, curvature)

        # Strip prefix
        et = text[text.find(prompt)+len(prompt):].strip() if prompt in text else text

        entry = {
            "tag": tag, "concept": concept, "prompt": prompt,
            "text": et[:200], "ksi_pre": float(kpi), "ksi_post": float(kpo),
            "lift": float(lift), "conf": float(conf), "variant": variant,
        }
        entries.append(entry)

        if (i+1) % 20 == 0:
            print(f"  {i+1}/{corpus_size}  ksi={kpi:.3f} conf={conf:.3f}  "
                  f"{tag}  {et[:60]}", flush=True)

    with open(args.output,'w') as f:
        for entry in entries:
            f.write(json.dumps(entry) + "\n")
    print(f"\n  Corpus: {len(entries)} entries → {args.output}")
    print(f"  Format: one JSON per line, 'tag' + 'text' for fine-tuning")
    print(f"\n  Fine-tuning recipe:")
    print(f"    Input:  <|ksi=0.547|><|conf=0.481|><|delta=+0.16|><|curve=0.008|> {prompt[:40]}...")
    print(f"    Target: next_token after the context")
    print(f"    Loss:   cross-entropy on the prediction of the NEXT KSI TAG")
    print(f"    After training: model predicts <|ksi=?|> before generating each token")
    print(f"    That prediction gates the confidence-resampling loop:")
    print(f"      predicted_ksi > current_ksi → stay on course")
    print(f"      predicted_ksi < current_ksi → the model predicts a drop → resample")

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    ap=argparse.ArgumentParser(description="Leyline GeM — Unified Architecture")
    ap.add_argument("cmd", choices=["run","burn_in"])
    ap.add_argument("--model",          required=True)
    ap.add_argument("--baseline_file",  required=True)
    ap.add_argument("--engram",         required=True)
    ap.add_argument("--bigram_db",      default=None)
    ap.add_argument("--field",          default=None)
    ap.add_argument("--system_prompt",  default=None)
    ap.add_argument("--prompt",         default="The cause of altruistic behavior is")
    ap.add_argument("--concept",        default="altruism")
    ap.add_argument("--arc_strength",   type=float, default=0.10)
    ap.add_argument("--max_tokens",     type=int,   default=120)
    ap.add_argument("--corpus_size",    type=int,   default=200)
    ap.add_argument("--output",         default="leyline_gem_out.json")
    args=ap.parse_args()
    {"run": cmd_run, "burn_in": cmd_burn_in}[args.cmd](args)

if __name__ == "__main__":
    main()
